### ISSUE TITLE
Coding ToDo list

### ISSUE THREAD

**Issue by imAlessas** [imAlessas/transmission-simulation#10]
**Task 1**
- [x] Draw a diagram of a digital information transmission system and describe in 1-2 sentences the purpose of each component.

**Task 2**
Prepare a calculation program for analysis of data source. Based on the specified probabilities of each symbol, calculate the following:
- [x] The source entropy and maximum possible value;
- [x] The source redundancy.

**Task 3**
Perform source encoding (Shannon-Fano) and improve the program from task 2, by calculating the following values:
- [x] Average codeword length
- [x] Probability of “1” and “0” symbol and binary entropy
- [x] Source data generation rate (after coding)
- [x] Compression ratio

**Task 4**
-Analyze Shannon theorem’s condition, by adding the following calculations into the program developed for Task 2 and Task 3:
- [x] Channel capacity without noise;
- [x] Bit Error Rate (BER) for specified SNR and modulation type;
- [x] Channel capacity with noise.
- [x] Make a conclusion, whether Shannon’s theorem condition is met or not, based on Your calculations.

**Task 5**
Analyze error correction code with specified parameters by performing coding and decoding operations for Your data block:
- [x] Encoding and writing systematic/non-systematic codeword
- [x] Decoding codeword without introduced errors;
- [x] Decoding codeword after introducing a single error
- [x] Decoding codeword after introducing a double error

**Task 6**
Develop a program for AWGN channel simulation with Your specified modulation type (cyclic-coding) and codeword length m. Simulate two cases:
- [x] without Hamming error correction code
- [x] with Hamming error correction code

**Task 7**
Calculate and plot modulated signal spectrums for Your specified parameters (symbol duration, modulation type, carrier frequency. Include in Your report following plots:
- [x] Magnitude (amplitude) spectrum for infinite periodic sequence “1 0 1 0 1 0 1 0 …”
- [x] Spectral Power Density (energy spectrum) for random sequence of “1” and “0”

**Task 8**
- [x] Evaluate the probability of more than 2 errors per codeword for Your specified Hamming code length and calculated BER value

**Additional Tasks**
- [x] Sequence generation function
- [x] Shannon encoding function
- [x] Shannon decoding function
- [x] Add padding bits function
- [x] Remove padding bits function
- [x] Interleaving function
- [x] Deinterleaving function
- [x] Scrumbling function
- [x] Descrumbling function
